on: push
name: Check Assignment
jobs:
  check-allowed-files:
    runs-on: self-hosted
    container:
      image: ghcr.io/dukestatsci/r_gh_actions:latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Check Files
      run: |
        checklist::quit_on_failure({
          checklist::check_allowed_files(c("hw-01.qmd", "hw-01.Rproj", "README.md", "data/napoleon.rds", "images/*.png"))
        })
      shell: Rscript {0}
  
  check-renders:
    runs-on: self-hosted
    container:
      image: ghcr.io/dukestatsci/r_gh_actions:latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Install Missing Packages
      run: |
        missing = checklist::install_missing_pkgs(dir = "./", glob = "hw-01.qmd")
      shell: Rscript {0}
    - name: Check Renders
      run: |
        checklist::check_qmd_renders("hw-01.qmd")
      shell: Rscript {0}
    - name: Create artifacts
      uses: actions/upload-artifact@v2
      with:
        name: hw-01-html
        path: hw-01.html